### PR TITLE
feat(*): add deploy service

### PR DESCRIPTION
**Pull request by andrewrynhard**
WIP

Wanted to throw this up here early to get your thoughts on it.

### CODE REVIEW

**Comment by rcarmstrong** [comment]
Hey Andrew, thanks for contributing! Couple things to think about here:
- It be great to have a test file that uses a httptest server to test the methods. (My test coverage is poor but I plan to do that for all services like I did for the comment/label services)
- The Bamboo API defaults to returning XML, so in the URLs you'll need to add .json to specify you want a json response.
- Because of the above, I found it cleaner to add the query parameters separately. I.e. when I add "max-results" to the plan service calls.

Feel free to share your thoughts on what I have so far. Any feed back is helpful!

**Comment by andrewrynhard** [comment]
Sounds good to me. I will get that up here when I have some more free time. FWIW, I have been successfully getting back JSON without the `.json`, but I like the idea of being more explicit anyways. Thanks!

**Review by rcarmstrong — APPROVED** [review]
Been awhile since I've been able to look this over. It looks good as is and I will merge it.

**Comment by andrewrynhard** [comment]
@rcarmstrong My apologies, I haven't had the time to make the changes you requested.

**Pull request merged**
